apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: connecting-worlds
    app.kubernetes.io/version: main
  name: connecting-worlds
  namespace: k8s-resources
data:
  application.yaml: |-
    app:
      chatbots:
        - name: fasty
          url:  http://fastify-chatbot.k8s-resources.svc.cluster.local/chat?message=
        - name: dotty
          url:  http://dotnet-chatbot.k8s-resources.svc.cluster.local/chat?message=
