# deployment-fastify-chatbot.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastify-chatbot
  namespace: k8s-resources
  labels:
    app.kubernetes.io/name: fastify-chatbot
    app.kubernetes.io/version: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fastify-chatbot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastify-chatbot
    spec:
      containers:
      - name: fastify-chatbot
        image: fs25group13.azurecr.io/fastify-chatbot:latest
        ports:
        - containerPort: 3000
        env:
        - name: LLM_API_KEY
          valueFrom:
            secretKeyRef:
              name: chatbot-api-keys
              key: fastify-chatbot-api-key
      imagePullSecrets:
      - name: acr-auth