# service-connecting-worlds.yaml
apiVersion: v1
kind: Service
metadata:
  name: connecting-worlds
  namespace: k8s-resources
  labels:
    app.kubernetes.io/name: connecting-worlds
    app.kubernetes.io/version: main
spec:
  selector:
    app.kubernetes.io/name: connecting-worlds
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP