apiVersion: v1
kind: Service
metadata:
  name: dotnet-chatbot
  namespace: k8s-resources
  labels:
    app.kubernetes.io/name: dotnet-chatbot
    app.kubernetes.io/version: main
spec:
  selector:
    app.kubernetes.io/name: dotnet-chatbot
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP